####################################################################################################
# Continuous Deployment [GitHub Metrics] Daily and on Push to Master
####################################################################################################
# References:
# - https://github.com/lowlighter/metrics
####################################################################################################
name: achievements
on:
  # Schedule updates daily at 00:00 AM
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push:
    branches: ["master"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          #----------------------------------------------
          # ----- Metrics Options -----
          #----------------------------------------------
          user: amirhessam88
          template: classic
          base: ""
          filename: assets/metrics_right.svg
          config_timezone: America/Chicago
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
